### PR TITLE
put on the hat

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by vmariano** [comment]
hat = cap?

**Comment by ramiror** [comment]
+1 to cap

**Comment by seppo0010** [comment]
I think the origin of the idiom refers to the police hats, not caps.
screen shot 2016-01-08 at 3 06 33 pm
screen shot 2016-01-08 at 3 06 38 pm

**Comment by ramiror** [comment]
hat it is. merged.

**Pull request merged**
